#连接端口配置
server:
  port: 8899

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///db_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=utc
    data-password: 123456
    data-username: root
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis配置
mybatis:
  config-location: classpath:mapper/**/*.xml
  type-aliases-package: com.spring.pojo
